server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: album-service
          uri: lb://album-service
          predicates:
            - Path=/albums/**
        - id: artist-service
          uri: lb://artist-service
          predicates:
            - Path=/artists/**
        - id: genre-service
          uri: lb://genre-service
          predicates:
            - Path=/genres/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
