server:
  port: 8082

spring:
  application:
    name: artist-service
  datasource:
    url: jdbc:postgresql://localhost:5434/album_db
    username: postgres
    password: Ansar0403
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
